Feature/logout bottom
yurii-horoshenko/BookMe pull request #34
Opened 2024-09-06 20:49 UTC by AndriiLatash

2024-09-07 09:58 UTC, AHuminskyi commented
Ticket: https://trello.com/c/0cAVOG8o

2024-09-07 10:10 UTC, AHuminskyi requested changes

2024-09-07 10:10 UTC, AHuminskyi commented on androidApp/src/main/java/com/gorosoft/bookme/now/android/ui/main_screen/profile/LogoutBottom.kt
> +            .border(1.dp, Color(0xFFF5F5F5)),
Оцей колір - це gs100 :)

2024-09-07 10:10 UTC, AHuminskyi commented on androidApp/src/main/java/com/gorosoft/bookme/now/android/ui/main_screen/profile/ProfileScreen.kt
> +            dragHandle = {
dragHandle - опціональне поле, яке по замовчуванню вже має значення в середині ModalBottomSheet, його точно треба робити пустим?

2024-09-07 10:12 UTC, AHuminskyi commented on androidApp/src/main/java/com/gorosoft/bookme/now/android/ui/main_screen/profile/LogoutBottom.kt
> +                .width(380.dp)
Тут повинно бути fillMaxWidth(), щоб дівайдер розтягувався на всю ширину ботом щита, але перед цим треба додати padding(horizontal = ...), щоб додати відступи зі сторін.

2024-09-07 14:29 UTC, AndriiLatash commented on androidApp/src/main/java/com/gorosoft/bookme/now/android/ui/main_screen/profile/LogoutBottom.kt
> +                .width(380.dp)
там якщо додаю padding(horizontal = ...), то в мене перестає працювати padding(top = ...), тому я просто залишив як було і додав тільки fillMaxWidth()

2024-09-07 19:11 UTC, AHuminskyi approved these changes

2024-09-09 19:52 UTC, kostasante approved these changes

2024-09-09 19:55 UTC, merged